### ISSUE TITLE
`let` regression for nested scopes

### ISSUE THREAD

**Issue by asaaki** [antonmi/espec#102]
Following example spec will fail if a `let` function name is used in another scope as variable name again:

#### Example spec

Smallest possible code to reproduce the regression:

```elixir
defmodule ExampleSpec do
  use ESpec

  describe "let and nesting" do
    describe "use let val" do
      let :result, do: 42

      it "is okay" do
        expect(result) |> to(eq 42)
      end
    end

    describe "use let name in example" do
      it "is not okay" do
        result = 23 # error!
        expect(result) |> to(eq 23)
      end
    end
  end
end
```

Steps for a reproducible project:

```
mix new espec_let_regression && cd espec_let_regression
# add espec dependency to mix.exs
mix deps.get
MIX_ENV=test mix espec.init
# replace example spec with code above
MIX_ENV=test mix espec
```

#### Error message

```
F.

	1) ExampleSpec ExampleSpec use let name in example is not okay
	/Users/chris/Development/PLAYGROUND/espec_let_regression/spec/example_spec.exs:14
	** (ESpec.LetError) The let function `result/0` is not defined in the current scope!
    (espec) lib/espec/let/checker.ex:12: ESpec.Let.Checker.check/3
    spec/example_spec.exs:14: ExampleSpec.example_is_not_okay_zrvdskjhfmyiaqcxwlptoneubg/1
    (espec) lib/espec/example_runner.ex:62: ESpec.ExampleRunner.try_run/3
    (espec) lib/espec/example_runner.ex:39: ESpec.ExampleRunner.run_example/2
    (elixir) lib/enum.ex:1088: Enum."-map/2-lists^map/1-0-"/2
    (espec) lib/espec/runner.ex:71: ESpec.Runner.run_examples/1
    (espec) lib/espec/runner.ex:44: ESpec.Runner.do_run/2
    (espec) lib/espec/runner.ex:30: ESpec.Runner.handle_call/3


	2 examples, 1 failures

	Finished in 0.17 seconds (0.14s on load, 0.02s on specs)

	Randomized with seed 457604
```

This error occurs also if the `let` and variable are spread across more levels of nesting, so I guess the `let`s are defined only globally for the spec module.

#### Expectation

Espec should respect the scoping and not try to use a `let` function name of another (not reachable) scope like seen above (sibling scopes).

I organize tests in nested scopes heavily and always try to define `let`s in the deepest level possible. I use common names (like _result_) quite often, but had to do renaming for examples which defined a variable name used already in another scope's `let`.

#### Environment

- **Espec: 0.8.18**
  (regression was introduced with 0.8.17; **0.8.16** and below are working!)
- Elixir: 1.2.5
- Erlang: 18.3
- System: OSX 10.10

**Comment by asaaki** [comment]
After some test runs against some commits it seems this regression was introduced with PR #95.

**Comment by antonmi** [comment]
Thanks, Christoph!
You are right.
The bug appeared after 'leaking let' had been fixed.

**Comment by antonmi** [comment]
I've fixed the problem.
Version 0.8.19 is released with the fix.
Please, test.
Thanks!

**Comment by asaaki** [comment]
It works for simple test suites, but in a [slightly bigger spec suite I still have some issues](https://travis-ci.org/edib-tool/mix-edib/builds/130218530).

I dug a bit into your recent change and found something.
I'll provide a PR for the change.

**Comment by asaaki** [comment]
I've opened #104, but even that does not fix all the issues.

After further investigation I found that assignments with pattern matches are an issue:

```elixir
defmodule ExampleSpec do
  use ESpec

  describe "EspecLetPlayground" do
    describe "let and nesting" do
      describe "use let val" do
        let :result, do: 42

        it "is okay" do
          expect(result) |> to(eq 42)
        end
      end

      describe "use let name in pattern match" do
        it "is not okay" do
          {:ok, result} = {:ok, 123} # this still fails
          expect(result) |> to(eq 123)
        end
      end
    end
  end
end
```

**Comment by antonmi** [comment]
Hi, Christoph!
The fix required more sophisticated assignment detection!
I've made changes in my last PR #105.
I also run your specs from https://travis-ci.org/edib-tool/mix-edib/builds/130218530
It seems to be ok now.
Please test the latest changes directly from master branch.
If all is good, I'll publish 0.8.20.

And thanks again for detailed description and examples!

**Comment by asaaki** [comment]
Local run as well as [travis build](https://travis-ci.org/edib-tool/mix-edib/builds/130412971) are green.
So I would say it is fixed now.

Thank you for this awesome tool, Anton! 🙇

**Comment by antonmi** [comment]
0.8.20 is published

**Comment by asaaki** [comment]
I also confirm that the published version is working. Closing this issue.
